name: edt-univ
channels:
  - numba
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python=3.10
  - pip
  - ipython
  - pre-commit
  - pyyaml
  - toml
  - xlsxwriter
  - scipy
  - pandas
  - ortools-python
  - xlrd
  - xlwt
  - pytables
  - black
  - openpyxl
  - scipy
  
