name: science
channels:
  - numba
  - conda-forge
  - rapidsai
  - nvidia
  - plotly
dependencies:
  - python=3.10
  - pip
  - ipython
  - nvidia::cuda=12.1
  - nvidia/label/cuda-12.1.1::cuda-nvcc
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pre-commit
  - pytest
  - rapids=24.02
  - dask 
  - dask-sql
  - dash
  - pycaret
  - xarray 
  - xarray-spatial
  - numba
  - pandas
  - yaml
  - scipy
  - jupyter
  - jupyterlab=3
  - jupyter-book
  - jupyterlab-git
  - sphinx-sitemap
  - ipywidgets=8
  - nodejs
  - ipympl
  - pytables
  - xlrd
  - xlwt
  - xlsxwriter
  - numpy
  - matplotlib
  - plotly
  - jinja2
  - tqdm
  - openpyxl
  - dtale
  - scikit-image
  - scikit-learn
  - seaborn 
  - pyarrow
  - colorcet
  - fast-histogram
  - pyviz::holoviews
  - sympy
  - myst-parser
  - ghp-import
  - sqlite
  - sqlalchemy
