name: science
channels:
  - numba
  - conda-forge
  - rapidsai
  - nvidia
  - plotly
dependencies:
  - python=3.10
  - pip
  - ipython
  # - nvidia::cuda=12.1
  # - nvidia/label/cuda-12.1.1::cuda-nvcc
  # - pytorch::pytorch
  # - pytorch::pytorch-cuda=12.1
  # - pytorch::torchvision
  # - pytorch::torchaudio
  - pre-commit
  - pytest
  # - rapids=24.02
  - jupyterlab=3
  - jupyter-book
  - jupyterlab-git
  - jupyter-server-proxy
  - sphinx-sitemap
  - ipywidgets=8
  - nodejs
  - ipympl
  # - dask-sql
  # - dash
  # - graphistry
  # - pycaret
  # - xarray-spatial
  - numba
  - pandas
  # - yaml
  # - scipy
  # - ipympl
  # - pytables
  # - xlrd
  # - xlwt
  # - xlsxwriter
  # - numpy
  # - matplotlib
  # - plotly
  # - tqdm
  # - openpyxl
  # - dtale
  # - scikit-image
  # - scikit-learn
  # - seaborn 
  # - pyarrow
  # - colorcet
  # - fast-histogram
  # - xarray 
  - dask 
  - pyvista
  - trame>=2.5.2
  - trame-vtk>=2.5.8
  - trame-vuetify>=2.3.1
  - trimesh
  - sympy
  - myst-parser
  - ghp-import

  
