name: science
channels:
  - numba
  - conda-forge
  - plotly
dependencies:
  - python=3.12
  - pip
  - ipython
  - pre-commit
  - pytest
  - xarray 
  - numba
  - pandas
  - yaml
  - scipy
  - just
  - sphinx
  - sphinx-sitemap
  - nbconvert
  - nodejs
  - ipympl
  - pytables
  - xlrd
  - xlwt
  - xlsxwriter
  - numpy
  - plotly
  - tqdm
  - jinja2
  - openpyxl
  - dtale
  - scikit-image
  - seaborn 
  - pyarrow
  - colorcet
  - sympy
  - myst-parser
  - ghp-import
  - sqlite
  - sqlalchemy
  - polars
