name: science
channels:
  - numba
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip
  - ipython
  - pre-commit
  - jupyter
  - numpy
  - matplotlib
  - scipy
  - pandas
  - pytest
  - dask
  - dask-sql
  - anaconda::sqlalchemy
  - dash
  - pycaret
  - xarray 
  - xarray-spatial
  - numba
  - yaml
  - jupyterlab=3
  - jupyter-book
  - jupyterlab-git
  - sphinx-sitemap
  - ipywidgets=8
  - nodejs
  - ipympl
  - pytables
  - xlrd
  - xlwt
  - xlsxwriter
  - plotly
  - tqdm
  - openpyxl
  - dtale
  - scikit-image
  - scikit-learn
  - seaborn 
  - pyarrow
  - colorcet
  - fast-histogram
  - sympy
  - pytorch::pytorch
  - myst-parser
  - ghp-import
